import HelperFunctions.Constants as Constants

NUMBER_OF_BLIND_ENTRIES = 8

BLIND_SETTINGS_CREATE_TABLE = """
create table if not exists
    BLIND_SETTINGS(
       BLIND_ID VARCHAR(20) PRIMARY KEY CHECK(TYPEOF(BLIND_ID) = 'text'),
       POSITION INTEGER NOT NULL CHECK(POSITION BETWEEN 0 AND 2)
    )"""



#Note, a where clause is not needed, will update all rows (1) in table  to these values
#This use case has only one row in the classroom table

BLIND_SETTINGS_SELECT = "SELECT * FROM BLIND_SETTINGS WHERE BLIND_ID = ?"

BLIND_SETTINGS_CHECK_NUMBER_OF_ROWS = "SELECT COUNT(*) FROM BLIND_SETTINGS"

BLIND_SETTINGS_INSERT = "INSERT INTO BLIND_SETTINGS VALUES(?, ?, ?)"

BLIND_SETTINGS_UPDATE = """
UPDATE BLIND_SETTINGS
SET
    POSITION = ?
WHERE BLIND_ID = ?
"""

BLIND_SETTINGS_DELETE = "DROP TABLE BLIND_SETTINGS"



#ROOM SETTINGS
NUMBER_OF_ROOM_SETTING_ENTRIES = 1

ROOM_SETTINGS_CHECK_NUMBER_OF_ROWS = "SELECT COUNT(*) FROM ROOM_SETTINGS"

ROOM_SETTINGS_CREATE_TABLE = """
create table if not exists
    ROOM_SETTINGS(
        ID INTEGER PRIMARY KEY CHECK(TYPEOF(ID) = 'integer' AND ID = 1),
        ROOM_ID VARCHAR(25) CHECK(TYPEOF(ROOM_ID) = 'text'),
        WIND_SPEED_AUTO_RAISE_THRESHOLD REAL CHECK(TYPEOF(WIND_SPEED_AUTO_RAISE_THRESHOLD) = 'real' AND WIND_SPEED_AUTO_RAISE_THRESHOLD >= 0.0),
        WIND_SPEED_LOWER_LOCK_THRESHOLD REAL CHECK(TYPEOF(WIND_SPEED_LOWER_LOCK_THRESHOLD) = 'real' AND WIND_SPEED_LOWER_LOCK_THRESHOLD >= 0.0)
    )
"""

ROOM_SETTINGS_SELECT = "SELECT * FROM ROOM_SETTINGS WHERE ID = 1"

ROOM_SETTINGS_INSERT = """
INSERT INTO ROOM_SETTINGS(
	ID,
	ROOM_ID,
	WIND_SPEED_AUTO_RAISE_THRESHOLD,
	WIND_SPEED_LOWER_LOCK_THRESHOLD)

	VALUES(?, ?, ?, ?)
"""


ROOM_SETTINGS_UPDATE_WIND_SPEED_AUTO_RAISE_THRESHOLD = """
UPDATE ROOM_SETTINGS
SET
    WIND_SPEED_AUTO_RAISE_THRESHOLD = ?
WHERE ID = 1
"""

ROOM_SETTINGS_UPDATE_WIND_SPEED_LOWER_LOCK_THRESHOLD = """
UPDATE ROOM_SETTINGS
SET
    WIND_SPEED_LOWER_LOCK_THRESHOLD = ?
WHERE ID = 1
"""


ROOM_SETTINGS_UPDATE_ROOM_ID = """
UPDATE ROOM_SETTINGS
SET
    ROOM_ID = ?
WHERE ID = 1
"""

ROOM_SETTINGS_DELETE = """
    DROP TABLE ROOM_SETTINGS
"""

#Sweep Settings

SWEEP_SETTINGS_CHECK_NUMBER_OF_ROWS = "SELECT COUNT(*) FROM SWEEP_SETTINGS"

SWEEP_SETTINGS_CREATE_TABLE = """
create table if not exists
    SWEEP_SETTINGS(
        READABLE_SWEEP_TIME VARCHAR(10) PRIMARY KEY CHECK(TYPEOF(READABLE_SWEEP_TIME) = 'text'),
        SWEEP_TIME VARCHAR(25) CHECK(TYPEOF(SWEEP_TIME) = 'text')
    )"""

SWEEP_SETTINGS_SELECT = "SELECT * FROM SWEEP_SETTINGS"

SWEEP_SETTINGS_SELECT_READABLE_SWEEP_TIME = "SELECT READABLE_SWEEP_TIME FROM SWEEP_SETTINGS"

SWEEP_SETTINGS_SELECT_SWEEP_TIME = "SELECT SWEEP_TIME FROM SWEEP_SETTINGS WHERE READABLE_SWEEP_TIME = ?"

SWEEP_SETTINGS_CHECK_IF_ENTRY_EXISTS = "SELECT SWEEP_TIME FROM SWEEP_SETTINGS WHERE SWEEP_TIME = ?"

SWEEP_SETTINGS_INSERT = """INSERT INTO SWEEP_SETTINGS(READABLE_SWEEP_TIME, SWEEP_TIME) VALUES(?, ?)"""

SWEEP_SETTINGS_DROP_TABLE = """
    DROP TABLE ROOM_SETTINGS
"""

SWEEP_SETTINGS_REMOVE_ROW = """DELETE FROM SWEEP_SETTINGS WHERE READABLE_SWEEP_TIME = ?"""
